// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7qbru5NnRu4OklKZLIt3ozcJDFUbp6qQ',
    appId: '1:762879021616:web:40c86ec8a57ec9b95893f5',
    messagingSenderId: '762879021616',
    projectId: 'attendanceapp-70175',
    authDomain: 'attendanceapp-70175.firebaseapp.com',
    storageBucket: 'attendanceapp-70175.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7vEhb_sU7qMkCEz4BZ878VoJRlHd_a70',
    appId: '1:762879021616:android:057ccedab8d0bdaf5893f5',
    messagingSenderId: '762879021616',
    projectId: 'attendanceapp-70175',
    storageBucket: 'attendanceapp-70175.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-H3NrHoTwCjex-bXePFocuFFCQcUKNE4',
    appId: '1:762879021616:ios:b0aaf3f07d6aeb2a5893f5',
    messagingSenderId: '762879021616',
    projectId: 'attendanceapp-70175',
    storageBucket: 'attendanceapp-70175.appspot.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-H3NrHoTwCjex-bXePFocuFFCQcUKNE4',
    appId: '1:762879021616:ios:85e86d65694d6c3f5893f5',
    messagingSenderId: '762879021616',
    projectId: 'attendanceapp-70175',
    storageBucket: 'attendanceapp-70175.appspot.com',
    iosBundleId: 'com.example.attendanceApp.RunnerTests',
  );
}
